working ensemble slice sampling
johnveitch/cpnest pull request #63
Opened 2020-02-21 19:31 UTC by wdpozzo

I implemented the ensemble slice sampling from https://arxiv.org/pdf/2002.06212v1.pdf. It seems to be stupidly efficient and passes  all tests up to d = 20

2020-02-21 19:31 UTC, pep8speaks commented
Hello @wdpozzo! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`cpnest/cpnest.py`](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py):

> [Line 63:1](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L63): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 65:80](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L65): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 66:1](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L66): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 91:24](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L91): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 91:24](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L91): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 91:32](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L91): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 93:27](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L93): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 93:27](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L93): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 93:32](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L93): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 107:80](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L107): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 109:80](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L109): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 171:41](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L171): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 191:41](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L191): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 193:58](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L193): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 195:35](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L195): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 196:35](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L196): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 196:42](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L196): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 196:42](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L196): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 196:48](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L196): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 197:35](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L197): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 197:41](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L197): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 197:41](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L197): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 197:48](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L197): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 198:35](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L198): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 198:43](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L198): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 198:43](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L198): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 198:48](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L198): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 199:35](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L199): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 199:39](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L199): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 199:39](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L199): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 199:48](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L199): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 200:35](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L200): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 200:43](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L200): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 200:43](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L200): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 200:48](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L200): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 201:35](https://github.com/johnveitch/cpnest/blob/e4402615c478a9cf02b05538a040cf64f7071d90/cpnest/cpnest.py#L201): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 201:46](https://github.com/johnve [...]

2020-02-22 09:53 UTC, wdpozzo commented
Incidentally, it turns out that logZ is unbiased if poolsize = 2*(dim + int(log2(dim))

2020-12-30 10:51 UTC, wdpozzo commented
@johnveitch : I pushed some fixes to this branch and now it passes all tests. The 50D gaussian evidence is unbiased and runs in ~10 minutes with 12 processes. Can you please review this and approve the pull request if you are happy?

2020-12-31 12:48 UTC, johnveitch requested changes
Excellent. I think you need to do a rebase or a merge to fix conflicts with master and there's a stray conflict in one of the files in the patch. I noted a couple of places  to remove commented code if it's not still useful.

2020-12-31 12:48 UTC, johnveitch commented on cpnest/cpnest.py
> +<<<<<<< HEAD
Looks like something went wrong here with a merge

2020-12-31 12:48 UTC, johnveitch commented on cpnest/nest2pos.py
> +#from statsmodels.tsa.ar_model import AutoReg
remove comment

2020-12-31 12:48 UTC, johnveitch commented on cpnest/nest2pos.py
> +#def acl_AR(x):
remove commented code

2021-01-04 10:49 UTC, wdpozzo commented
@johnveitch : I rebased against master and verified that it is still working. I also took care of your comments.

2021-01-07 08:57 UTC, wdpozzo commented on cpnest/nest2pos.py
> +#def acl_AR(x):
done

2021-01-07 08:57 UTC, wdpozzo commented on cpnest/nest2pos.py
> +#from statsmodels.tsa.ar_model import AutoReg
done

2021-01-07 08:57 UTC, wdpozzo commented on cpnest/cpnest.py
> +<<<<<<< HEAD
fixed

2021-01-08 15:41 UTC, johnveitch commented
I added a couple of test programs for the slice sampler and all looks good!

2021-01-08 15:41 UTC, merged